### ISSUE TITLE
[Bug] Local activity marker parsing issue on signal receipt

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#354]
### Describe the bug

When starting a workflow that runs a local activity to completion in a task and then receives a signal, the workflow is evicted with:

> Error while updating workflow: Nondeterminism("Local activity machine encountered an unparsable marker")

### Minimal Reproduction

In Python:

```python
@activity.defn
async def my_activity() -> None:
    pass

@workflow.defn
class MyWorkflow:
    def __init__(self) -> None:
        self._finish = asyncio.Event()

    @workflow.run
    async def run(self) -> None:
        await workflow.execute_local_activity(
            my_activity, start_to_close_timeout=timedelta(seconds=5)
        )
        await self._finish.wait()

    @workflow.signal
    def finish(self) -> None:
        self._finish.set()

async def test_my_workflow(client: Client):
    async with Worker(
        client,
        task_queue=f"task_queue_{uuid.uuid4()}",
        workflows=[MyWorkflow],
        activities=[my_activity],
    ) as worker:
        # Start the workflow
        handle = await client.start_workflow(
            MyWorkflow.run, id=f"workflow_{uuid.uuid4()}", task_queue=worker.task_queue
        )
        # Wait 2 seconds
        await asyncio.sleep(2)
        # Send signal and wait for complete
        await handle.signal(MyWorkflow.finish)
        await handle.result()
```

### Environment/Versions

Latest core and Python SDK

### Additional context

History attached at [workflow_history.json.txt](https://github.com/temporalio/sdk-core/files/9121537/workflow_history.json.txt) (ignore the wft timeouts at the end, I killed the worker)

**Comment by cretz** [comment]
Below are the collapsed logs with activations and completions (only up to the second failed WFT).

<details>
  <summary>Logs</summary>
  
```
11:21:08 [   DEBUG] Received workflow activation:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
timestamp {
  seconds: 1657902068
  nanos: 367406800
}
history_length: 3
jobs {
  start_workflow {
    workflow_type: "MyWorkflow"
    workflow_id: "workflow_9ed96113-4f83-4bf0-a837-9a91ce6aff69"
    randomness_seed: 14335373661824764744
    identity: "38096@cretz-laptop"
    workflow_task_timeout {
      seconds: 10
    }
    first_execution_run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
    attempt: 1
    cron_schedule_to_schedule_interval {
    }
  }
}
 (workflow.py:147)
11:21:08 [   DEBUG] Sending workflow completion:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
successful {
  commands {
    schedule_local_activity {
      seq: 1
      activity_id: "1"
      activity_type: "my_activity"
      start_to_close_timeout {
        seconds: 5
      }
      retry_policy {
      }
    }
  }
}
 (workflow.py:215)
11:21:08 [   DEBUG] Running activity my_activity (token b'local_act_\x01\x00\x00\x00') (activity.py:246)
11:21:08 [   DEBUG] Starting activity ({'activity_id': '1', 'activity_type': 'my_activity', 'attempt': 1, 'namespace': 'test-namespace-77106f41-a3ae-4f70-9fb4-06ff76d1de67', 'task_queue': 'task_queue_38212bfc-2233-41e5-a17d-09af5ef1f442', 'workflow_id': 'workflow_9ed96113-4f83-4bf0-a837-9a91ce6aff69', 'workflow_run_id': 'dc00a963-0cd9-4095-8dca-7b6778439e47', 'workflow_type': 'MyWorkflow'}) (activity.py:388)
11:21:08 [   DEBUG] Completing activity with completion: task_token: "local_act_\001\000\000\000"
result {
  completed {
  }
}
 (activity.py:475)
11:21:08 [   DEBUG] Received workflow activation:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
timestamp {
  seconds: 1657902068
  nanos: 372741100
}
history_length: 3
jobs {
  resolve_activity {
    seq: 1
    result {
      completed {
      }
    }
  }
}
 (workflow.py:147)
11:21:08 [   DEBUG] Sending workflow completion:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
successful {
}
 (workflow.py:215)
11:21:10 [   DEBUG] Received workflow activation:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
timestamp {
  seconds: 1657902068
  nanos: 372741100
}
is_replaying: true
history_length: 4
jobs {
  remove_from_cache {
    message: "Error while updating workflow: Nondeterminism(\"Local activity machine encountered an unparsable marker\")"
    reason: NONDETERMINISM
  }
}
 (workflow.py:147)
11:21:10 [   DEBUG] Sending workflow completion:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
successful {
}
 (workflow.py:215)
11:21:10 [   DEBUG] Evicting workflow with run ID dc00a963-0cd9-4095-8dca-7b6778439e47, message: Error while updating workflow: Nondeterminism("Local activity machine encountered an unparsable marker") (workflow.py:226)
11:21:20 [   DEBUG] Received workflow activation:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
timestamp {
  seconds: 1657902068
  nanos: 367406800
}
is_replaying: true
history_length: 3
jobs {
  remove_from_cache {
    message: "Error while updating workflow: Fatal(\"Local activity marker was unparsable: HistoryEvent { event_id: 5, event_time: Some(Timestamp { seconds: 1657902068, nanos: 413900200 }), event_type: MarkerRecorded, version: 0, task_id: 1048585, attributes: Some(MarkerRecordedEventAttributes(MarkerRecordedEventAttributes { marker_name: \\\"core_local_activity\\\", details: {\\\"data\\\": Payloads { payloads: [Payload { metadata: {\\\"encoding\\\": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [123, 34, 115, 101, 113, 34, 58, 49, 44, 34, 97, 116, 116, 101, 109, 112, 116, 34, 58, 49, 44, 34, 97, 99, 116, 105, 118, 105, 116, 121, 95, 105, 100, 34, 58, 34, 49, 34, 44, 34, 97, 99, 116, 105, 118, 105, 116, 121, 95, 116, 121, 112, 101, 34, 58, 34, 109, 121, 95, 97, 99, 116, 105, 118, 105, 116, 121, 34, 44, 34, 99, 111, 109, 112, 108, 101, 116, 101, 95, 116, 105, 109, 101, 34, 58, 123, 34, 115, 101, 99, 111, 110, 100, 115, 34, 58, 49, 54, 53, 55, 57, 48, 50, 48, 54, 56, 44, 34, 110, 97, 110, 111, 115, 34, 58, 51, 55, 50, 55, 52, 49, 49, 48, 48, 125, 44, 34, 98, 97, 99, 107, 111, 102, 102, 34, 58, 110, 117, 108, 108, 44, 34, 111, 114, 105, 103, 105, 110, 97, 108, 95, 115, 99, 104, 101, 100, 117, 108, 101, 95, 116, 105, 109, 101, 34, 58, 123, 34, 115, 101, 99, 111, 110, 100, 115, 34, 58, 49, 54, 53, 55, 57, 48, 50, 48, 54, 56, 44, 34, 110, 97, 110, 111, 115, 34, 58, 51, 57, 54, 55, 48, 56, 55, 48, 48, 125, 125] }] }}, workflow_task_completed_event_id: 4, header: None, failure: None })) }\")"
    reason: FATAL
  }
}
 (workflow.py:147)
11:21:20 [   ERROR] Failed handling activation on workflow with run ID dc00a963-0cd9-4095-8dca-7b6778439e47 (workflow.py:178)
Traceback (most recent call last):
  File "C:\work\tem\python-otel\temporal-sdk-python\temporalio\worker\workflow.py", line 152, in _handle_activation
    workflow = await self._create_workflow_instance(act)
  File "C:\work\tem\python-otel\temporal-sdk-python\temporalio\worker\workflow.py", line 237, in _create_workflow_instance
    raise RuntimeError(
RuntimeError: Missing start workflow, workflow could have unexpectedly been removed from cache
11:21:20 [   DEBUG] Sending workflow completion:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
failed {
  failure {
    message: "Missing start workflow, workflow could have unexpectedly been removed from cache"
    stack_trace: "  File \"C:\\work\\tem\\python-otel\\temporal-sdk-python\\temporalio\\worker\\workflow.py\", line 152, in _handle_activation\n    workflow = await self._create_workflow_instance(act)\n\n  File \"C:\\work\\tem\\python-otel\\temporal-sdk-python\\temporalio\\worker\\workflow.py\", line 237, in _create_workflow_instance\n    raise RuntimeError(\n"
    application_failure_info {
      type: "RuntimeError"
    }
  }
}
 (workflow.py:215)
11:21:20 [   DEBUG] Received workflow activation:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
timestamp {
  seconds: 1657902068
  nanos: 367406800
}
is_replaying: true
history_length: 3
jobs {
  remove_from_cache {
    message: "Error while updating workflow: Fatal(\"Local activity marker was unparsable: HistoryEvent { event_id: 5, event_time: Some(Timestamp { seconds: 1657902068, nanos: 413900200 }), event_type: MarkerRecorded, version: 0, task_id: 1048585, attributes: Some(MarkerRecordedEventAttributes(MarkerRecordedEventAttributes { marker_name: \\\"core_local_activity\\\", details: {\\\"data\\\": Payloads { payloads: [Payload { metadata: {\\\"encoding\\\": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [123, 34, 115, 101, 113, 34, 58, 49, 44, 34, 97, 116, 116, 101, 109, 112, 116, 34, 58, 49, 44, 34, 97, 99, 116, 105, 118, 105, 116, 121, 95, 105, 100, 34, 58, 34, 49, 34, 44, 34, 97, 99, 116, 105, 118, 105, 116, 121, 95, 116, 121, 112, 101, 34, 58, 34, 109, 121, 95, 97, 99, 116, 105, 118, 105, 116, 121, 34, 44, 34, 99, 111, 109, 112, 108, 101, 116, 101, 95, 116, 105, 109, 101, 34, 58, 123, 34, 115, 101, 99, 111, 110, 100, 115, 34, 58, 49, 54, 53, 55, 57, 48, 50, 48, 54, 56, 44, 34, 110, 97, 110, 111, 115, 34, 58, 51, 55, 50, 55, 52, 49, 49, 48, 48, 125, 44, 34, 98, 97, 99, 107, 111, 102, 102, 34, 58, 110, 117, 108, 108, 44, 34, 111, 114, 105, 103, 105, 110, 97, 108, 95, 115, 99, 104, 101, 100, 117, 108, 101, 95, 116, 105, 109, 101, 34, 58, 123, 34, 115, 101, 99, 111, 110, 100, 115, 34, 58, 49, 54, 53, 55, 57, 48, 50, 48, 54, 56, 44, 34, 110, 97, 110, 111, 115, 34, 58, 51, 57, 54, 55, 48, 56, 55, 48, 48, 125, 125] }] }}, workflow_task_completed_event_id: 4, header: None, failure: None })) }\")"
    reason: FATAL
  }
}
 (workflow.py:147)
11:21:20 [   ERROR] Failed handling activation on workflow with run ID dc00a963-0cd9-4095-8dca-7b6778439e47 (workflow.py:178)
Traceback (most recent call last):
  File "C:\work\tem\python-otel\temporal-sdk-python\temporalio\worker\workflow.py", line 152, in _handle_activation
    workflow = await self._create_workflow_instance(act)
  File "C:\work\tem\python-otel\temporal-sdk-python\temporalio\worker\workflow.py", line 237, in _create_workflow_instance
    raise RuntimeError(
RuntimeError: Missing start workflow, workflow could have unexpectedly been removed from cache
11:21:20 [   DEBUG] Sending workflow completion:
run_id: "dc00a963-0cd9-4095-8dca-7b6778439e47"
failed {
  failure {
    message: "Missing start workflow, workflow could have unexpectedly been removed from cache"
    stack_trace: "  File \"C:\\work\\tem\\python-otel\\temporal-sdk-python\\temporalio\\worker\\workflow.py\", line 152, in _handle_activation\n    workflow = await self._create_workflow_instance(act)\n\n  File \"C:\\work\\tem\\python-otel\\temporal-sdk-python\\temporalio\\worker\\workflow.py\", line 237, in _create_workflow_instance\n    raise RuntimeError(\n"
    application_failure_info {
      type: "RuntimeError"
    }
  }
}
 (workflow.py:215)
```
</details>

This also causes a double `remove_from_cache` which my code doesn't know how to handle so it keeps trying.
