### ISSUE TITLE
[Bug] thread 'core' panicked at 'Send half of activation complete response not dropped

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-core#526]
Error: thread 'core' panicked at 'Send half of activation complete response not dropped: RecvError(())', sdk-core/core/src/worker/workflow/mod.rs:350:14

SDK: Typescript
Worker deployment on EKS.

Environment

```
Versions in package.json:
        "@temporalio/activity": "^1.5.2",
        "@temporalio/client": "^1.5.2",
        "@temporalio/worker": "^1.5.2",
        "@temporalio/workflow": "^1.5.2",

yarn.lock
"@temporalio/worker@npm:^1.4.4":
  version: 1.4.4
  resolution: "@temporalio/worker@npm:1.4.4"
  dependencies:
    "@opentelemetry/api": ^1.1.0
    "@swc/core": ^1.2.204
    "@temporalio/activity": ~1.4.4
    "@temporalio/common": ~1.4.4
    "@temporalio/core-bridge": ~1.4.4
    "@temporalio/proto": ~1.4.4
    "@temporalio/workflow": ~1.4.4
    abort-controller: ^3.0.0
    cargo-cp-artifact: ^0.1.6
    heap-js: ^2.2.0
    memfs: ^3.4.6
    ms: ^2.1.3
    rxjs: ^7.5.5
    semver: ^7.3.7
    source-map: ^0.7.4
    source-map-loader: ^4.0.0
    swc-loader: ^0.2.3
    terser: ^5.14.2
    unionfs: ^4.4.0
    webpack: ^5.73.0
  checksum: 0a74179095298c0525ac363066b23a978443158367007d7fc3f5aafe0d7a9d501b0c99ac4542cc5df20545ea8edc00564dc9fa32c5e158c3ecdc8f0a81e3eeee
  languageName: node
  linkType: hard
```

**Comment by jcgsville** [comment]
Hi Temporal sdk team 👋 

Here's some more details:

We're running on `public.ecr.aws/docker/library/node:16-slim` on `--platform=linux/amd64`

We believe we are encountering this error when one of our workers picks up a workflow task and triggers a non-determinism error. My team is currently working on a minimal repro of a workflow that has the NDE and triggers the panic.

Here's an example of an NDE error we're seeing in the workflow

```
Nondeterminism error: Search attribute upsert calls must remain deterministic, but SearchAttributes { indexed_fields: {\"workflowTypeText\": Payload { metadata: {\"encoding\": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} } does not match the attributes from history: SearchAttributes { indexed_fields: {\"workflowTypeText\": Payload { metadata: {\"encoding\": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110], \"type\": [84, 101, 120, 116]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} }"
```

And another example

```
Nondeterminism(\"UpsertWorkflowSearchAttributesMachine does not handle HistoryEvent(id: 6, Some(MarkerRecorded))\")
```

The interesting thing about both these examples is the following: even though they are at different errors, they are both what I think would happen if a version of the workflow code from ~2 weeks ago was running before we introduced in one commit the following changes:

1. We introduced a GZIP codec that compresses the event payloads. The attributes of the event in the history have a value at Payload.metadata.type of `text`, wheras the new event attribute looks to be using the gzip codec

<details>
  <summary>For reference, here are the contents of the GZip codec
</summary>
  
```ts
import { gzip, ungzip} from 'node-gzip'
import { METADATA_ENCODING_KEY, Payload, PayloadCodec, ValueError } from '@temporalio/common'
import { temporal } from '@temporalio/proto'
import { decode, encode } from '@temporalio/common/lib/encoding'

export const ENCODING = 'gzip'


const toUint8Array = (buffer: Buffer): Uint8Array => new Uint8Array(buffer)

const toBuffer = (uint8Array: Uint8Array): Buffer => {
    const buffer = Buffer.alloc(uint8Array.byteLength)

    for (let idx = 0; idx < buffer.length; idx = idx + 1) {
        buffer[idx] = uint8Array[idx] as number
    }

    return buffer
}

export class GZipCodec implements PayloadCodec {
    async encode(payloads: Payload[]): Promise<Payload[]> {
        return Promise.all(
            payloads.map(async payload => ({
                metadata: {
                    [METADATA_ENCODING_KEY]: encode(ENCODING),
                },
                // Encrypt entire payload, preserving metadata
                data: toUint8Array(await gzip(
                    temporal.api.common.v1.Payload.encode(payload).finish(),
                )),
            }))
        )
    }

    async decode(payloads: Payload[]): Promise<Payload[]> {
        return Promise.all(
            payloads.map(async payload => {
                if (
                    !payload.metadata ||
                    (payload.metadata[METADATA_ENCODING_KEY] &&
                        decode(payload.metadata[METADATA_ENCODING_KEY]) !== ENCODING)
                ) {
                    return payload
                }

                if (!payload.data) {
                    throw new ValueError('Payload data is missing')
                }

                const decryptedPayloadBytes = await ungzip(toBuffer(payload.data))

                return temporal.api.common.v1.Payload.decode(decryptedPayloadBytes)
            })
        )
    }
}
```

</details>

2. We added a `if (patch('some-val')` statement before calling the search attributes

It's happened twice that these NDEs and the panics coincide, but we of course don't know causation for sure. My best guess right now is that something is causing some workflows to be started with old worker code, those workflows are being picked up by the new, correct, workers, and they are failing with an NDE on replay. For some reason, that NDE is causing a panic.

BUT, we were able to reproduce it this morning in a non-prod EKS environment pointed against a different temporal cloud namespace. This seems to lessen the likelihood that it's some old code running.

**Comment by jcgsville** [comment]
We're going to add RUST_BACKTRACE to see if that gives us anything more helpful for you

**Comment by jcgsville** [comment]
```
Worker state changed
Worker failed
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
9: tokio::runtime::task::raw::poll
8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
7: tokio::runtime::task::raw::poll
6: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
5: <futures_util::stream::stream::for_each_concurrent::ForEachConcurrent<St,Fut,F> as core::future::future::Future>::poll
4: <temporal_sdk_core::worker::Worker as temporal_sdk_core_api::Worker>::complete_workflow_activation::{{closure}}
3: temporal_sdk_core::worker::workflow::Workflows::activation_completed::{{closure}}.49447
at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
2: core::result::unwrap_failed
at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
1: core::panicking::panic_fmt
at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
0: rust_begin_unwind
Setup flow is already running.
Activity failed
stack backtrace:
thread 'core' panicked at 'Send half of activation complete response not dropped: RecvError(())', sdk-core/core/src/worker/workflow/mod.rs:350:14
```

**Comment by Sushisource** [comment]
@jcgsville Thanks for reporting this - you're a couple TS releases behind, I'd definitely try upgrading and see if that changes anything for you. That said, the other thing that would be useful to do is see if there are any errors earlier in the log, because likely something else wrong would've needed to happen to precipitate this panic.

That aside, I'll also make a change to not panic in this situation. It can be handled more gracefully, even if it shouldn't happen at all.

**Comment by jcgsville** [comment]
I'm not certain if this is a problem on your end or mine, but just upgrading from 1.4.4 to 1.7.0 seems to have triggered this error

```
Error: duplicate name 'ActivityHeartbeat' in Namespace coresdk
```

(Working on something else related to our outage at the moment, I'll report back on any logs leading up to the panics in a bit)

**Comment by jcgsville** [comment]
Hi @Sushisource, we're working on upgrading our workers. In the meantime, here's the logs from one of our pods in the 10 minute window surrounding the panic. There's not really much more info in there:

```csv
Date,Message
2023-04-06T19:14:19.137Z,"note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace."
2023-04-06T19:14:19.137Z,3: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
2023-04-06T19:14:19.137Z,at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
2023-04-06T19:14:19.137Z,2: core::result::unwrap_failed
2023-04-06T19:14:19.137Z,at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
2023-04-06T19:14:19.137Z,1: core::panicking::panic_fmt
2023-04-06T19:14:19.137Z,at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
2023-04-06T19:14:19.137Z,0: rust_begin_unwind
2023-04-06T19:14:19.137Z,stack backtrace:
2023-04-06T19:14:19.137Z,"thread '<unnamed>' panicked at 'Activation processor channel not dropped: SendError(Ok(LangActivation(WorkflowActivation { run_id: ""98dcf70d-dc91-401f-b527-2da07ce9757d"", timestamp: Some(Timestamp { seconds: 1680808458, nanos: 439403916 }), is_replaying: false, history_length: 3, jobs: [WorkflowActivationJob { variant: Some(StartWorkflow(StartWorkflow { workflow_type: ""handleCw1OrganizationMessageWorkflow"", workflow_id: ""9eaa24c9-2db1-477d-9e7e-2664a4821070|ORGANIZATION"", arguments: [Payload { metadata: {""encoding"": [103, 122, 105, 112]}, data: [31, 139, 8, 0, 0, 0, 0, 0, 0, 19, 213, 151, 77, 111, 27, 71, 12, 134, 175, 133, 143, 57, 244, 94, 157, 205, 100, 190, 201, 241, 205, 41, 212, 70, 104, 108, 57, 182, 209, 75, 81, 20, 156, 47, 119, 107, 89, 50, 180, 18, 146, 32, 240, 239, 235, 223, 42, 237, 228, 16, 8, 82, 188, 151, 8, 149, 14, 130, 32, 44, 249, 206, 59, 243, 12, 201, 61, 250, 241, 232, 135, 58, 207, 139, 210, 205, 111, 94, 28, 253, 211, 47, 230, 175, 238, 103, 220, 205, 95, 252, 251, 211, 167, 81, 55, 239, 86, 29, 207, 206, 106, 223, 243, 77, 125, 183, 174, 235, 58, 58, 249, 227, 211, 232, 238, 243, 31, 163, 147, 199, 71, 86, 245, 102, 201, 171, 110, 49, 159, 148, 209, 201, 40, 86, 102, 227, 114, 4, 83, 146, 6, 135, 88, 32, 86, 172, 96, 66, 112, 236, 200, 104, 133, 106, 116, 60, 202, 239, 245, 68, 34, 151, 249, 111, 158, 223, 212, 235, 37, 231, 91, 89, 192, 83, 6, 114, 214, 42, 99, 16, 168, 81, 4, 231, 43, 66, 196, 168, 32, 230, 98, 28, 215, 168, 116, 101, 201, 240, 101, 13, 79, 33, 25, 117, 113, 133, 42, 20, 246, 22, 124, 114, 10, 152, 178, 3, 141, 10, 209, 89, 69, 86, 147, 132, 244, 11, 190, 63, 251, 42, 108, 160, 82, 191, 88, 47, 179, 152, 29, 157, 79, 175, 39, 191, 76, 126, 62, 189, 158, 76, 207, 255, 186, 58, 63, 189, 184, 122, 51, 189, 150, 7, 86, 143, 203, 191, 88, 46, 178, 228, 22, 23, 151, 181, 95, 207, 86, 253, 232, 164, 241, 172, 175, 18, 111, 31, 55, 42, 173, 243, 109, 93, 73, 150, 217, 135, 4, 43, 190, 3, 217, 2, 184, 231, 101, 95, 11, 172, 123, 168, 220, 175, 192, 188, 156, 45, 110, 186, 15, 105, 193, 203, 242, 50, 47, 238, 36, 247, 109, 253, 56, 112, 87, 95, 13, 178, 243, 112, 252, 245, 145, 141, 231, 171, 110, 245, 241, 105, 51, 208, 56, 108, 138, 13, 228, 134, 13, 156, 113, 1, 162, 14, 6, 18, 99, 12, 108, 163, 43, 42, 124, 142, 238, 235, 114, 85, 203, 117, 119, 87, 207, 186, 217, 172, 19, 163, 58, 144, 66, 114, 134, 148, 124, 30, 142, 191, 51, 32, 58, 27, 57, 87, 239, 161, 168, 150, 192, 149, 226, 128, 149, 38, 176, 217, 6, 27, 19, 18, 182, 186, 1, 72, 105, 70, 155, 136, 25, 154, 21, 135, 158, 108, 4, 66, 141, 80, 93, 68, 74, 177, 25, 175, 202, 22, 64, 6, 42, 109, 7, 100, 252, 251, 248, 252, 127, 68, 199, 32, 47, 59, 233, 24, 159, 94, 93, 92, 78, 95, 79, 175, 158, 69, 64, 239, 3, 1, 171, 18, 22, 237, 10, 212, 134, 22, 92, 114, 194, 169, 179, 21, 130, 211, 200, 136, 85, 220, 233, 13, 4, 188, 107, 28, 124, 206, 64, 172, 18, 248, 18, 157, 132, 52, 2, 34, 93, 188, 172, 1, 75, 217, 134, 192, 64, 165, 67, 169, 17, 131, 236, 236, 164, 32, 86, 98, 237, 51, 67, 206, 242, 229, 144, 2, 36, 157, 10, 56, 157, 11, 113, 72, 216, 242, 51, 53, 34, 146, 242, 251, 0, 164, 22, 194, 42, 69, 12, 146, 101, 201, 144, 165, 32, 178, 242, 25, 140, 92, 125, 103, 189, 110, 142, 212, 6, 32, 209, 214, 72, 90, 90, 7, 97, 100, 105, 34, 153, 32, 82, 201, 224, 93, 174, 190, 149, 42, 100, 167, 45, 128, 12, 84, 58, 136, 26, 49, 200, 203, 78, 58, 174, 222, 78, 95, 143, 199, 207, 214, 136, 125, 33, 224, 217, 228, 88, 21, 130, 206, 49, 8, 234, 41, 65, 20, 93, 57, 207, 98, 41, 90, 102, 173, 195, 6, 2, 76, 206, 7, 149, 27, 20, 157, 165, 70, 72, 203, 16, 24, 88, 170, 165, 171, 220, 124, 33, 227, 217, 111, 65, 96, 160, 210, 161, 212, 136, 65, 118, 118, 82, 192, 145, 139, 55, 42, 128, 143, 73, 162, 177, 60, 206, 98, 70, 196, 154, 97, 149, 157, 92, 43, 139, 223, 4, 36, 42, 143, 184, 15, 64, 2, 86, 155, 29, 55, 80, 86, 154, 161, 84, 65, 3, 228, 49, 129, 197, 230, 101, 34, 224, 156, 112, 115, 208, 84, 70, 91, 42, 149, 193, 100, 213, 192, 27, 1, 132, 179, 152, 227, 170, 170, 143, 148, 154, 211, 110, 11, 32, 3, 149, 14, 5, 144, 65, 118, 190, 47, 32, 180, 151, 65, 211, 53, 101, 173, 110, 114, 188, 14, 193, 177, 177, 242, 75, 70, 38, 116, 37, 162, 100, 38, 166, 205, 65, 211, 202, 13, 145, 62, 225, 101, 198, 124, 116, 24, 66, 134, 132, 150, 32, 228, 148, 92, 46, 49, 91, 220, 246, 38, 50, 80, 233, 80, 0, 25, 100, 103, 39, 32, 146, 158, 76, 78, 17, 100, 180, 48, 34, 97, 229, 126, 81, 11, 16, 228, 197, 132, 101, 120, 105, 66, 223, 183, 1, 137, 65, 250, 248, 62, 0, 137, 45, 88, 244, 26, 84, 73, 242, 206, 84, 165, 92, 202, 241, 123, 80, 38, 166, 68, 177, 144, 204, 154, 27, 128, 160, 18, 87, 73, 68, 155, 150, 151, 16, 233, 39, 5, 200, 233, 4, 181, 134, 40, 118, 229, 94, 100, 189, 13, 144, 97, 74, 7, 49, 101, 12, 242, 178, 147, 142, 95, 47, 199, 111, 79, 127, 155, 156, 190, 121, 22, 129, 167, 41, 227, 207, 135, 255, 0, 116, 196, 78, 148, 226, 16, 0, 0] }], randomness_seed: 8047213567501658315, headers: {}, identity: ""11221@Estebans-MBP-2.fritz.box"", parent_workflow_info: None, workflow_execution_timeout: None, workflow_run_timeout: None, workflow_task_timeout: Some(Duration { seconds: 10, nanos: 0 }), continued_from_execution_run_id: """", continued_initiator: Unspecified, continued_failure: None, last_completion_result: None, first_execution_run_id: ""98dcf70d-dc91-401f-b527-2da07ce9757d"", retry_policy: None, attempt: 1, cron_schedule: """", workflow_execution_expiration_time: None, cron_schedule_to_schedule_interval: Some(Duration { seconds: 0, nanos: 0 }), memo: None, search_attributes: None, start_time: Some(Timestamp { seconds: 1680808458, nanos: 177213047 }) })) }], available_internal_flags: [] })))', sdk-core/core/src/worker/workflow/mod.rs:243:38"
2023-04-06T19:14:19.137Z,"note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace."
2023-04-06T19:14:19.137Z,9: tokio::runtime::task::raw::poll
2023-04-06T19:14:19.137Z,8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
2023-04-06T19:14:19.137Z,7: tokio::runtime::task::raw::poll
2023-04-06T19:14:19.137Z,6: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2023-04-06T19:14:19.137Z,"5: <futures_util::stream::stream::for_each_concurrent::ForEachConcurrent<St,Fut,F> as core::future::future::Future>::poll"
2023-04-06T19:14:19.137Z,4: <temporal_sdk_core::worker::Worker as temporal_sdk_core_api::Worker>::complete_workflow_activation::{{closure}}
2023-04-06T19:14:19.137Z,3: temporal_sdk_core::worker::workflow::Workflows::activation_completed::{{closure}}.49447
2023-04-06T19:14:19.137Z,at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
2023-04-06T19:14:19.137Z,2: core::result::unwrap_failed
2023-04-06T19:14:19.137Z,at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
2023-04-06T19:14:19.137Z,1: core::panicking::panic_fmt
2023-04-06T19:14:19.137Z,at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
2023-04-06T19:14:19.137Z,0: rust_begin_unwind
2023-04-06T19:14:19.137Z,stack backtrace:
2023-04-06T19:14:19.137Z,"thread 'core' panicked at 'Send half of activation complete response not dropped: RecvError(())', sdk-core/core/src/worker/workflow/mod.rs:350:14"
2023-04-06T19:14:19.137Z,"[2m2023-04-06T19:14:18.456440Z[0m [31mERROR[0m [1mcomplete_workflow_activation[0m: [1mtemporal_sdk_core::worker::workflow::workflow_stream[0m[2m:[0m Run missing during completion New(WFActCompleteMsg { completion: Success { run_id: ""76211661-5bc2-4d35-9fdd-200cc36df75b"", commands: [], used_flags: [] }, response_tx: Some(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) }) }) [2m[3mcompletion[0m[2m=[0mWorkflowActivationCompletion(run_id: 76211661-5bc2-4d35-9fdd-200cc36df75b, status: Success()) [3mrun_id[0m[2m=[0m76211661-5bc2-4d35-9fdd-200cc36df75b [3mtask_queue[0m[2m=[0mcw1_organization_entity_workflows|us-east-2.logixboard.com[0m"
2023-04-06T19:14:19.137Z,"[2m2023-04-06T19:14:18.455792Z[0m [33m WARN[0m [1mnext_workflow_activation[0m: [1mtemporal_sdk_core::worker::workflow[0m[2m:[0m Failing workflow task [3mrun_id[0m[2m=[0m5c97d62f-71b8-482d-a846-455a496c6e8b [3mfailure[0m[2m=[0mFailure { failure: Some(Failure { message: ""Error while processing workflow task"", source: ""Nondeterminism error: Search attribute upsert calls must remain deterministic, but SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} } does not match the attributes from history: SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""type\"": [84, 101, 120, 116], \""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} }"", stack_trace: """", encoded_attributes: None, cause: None, failure_info: None }), force_cause: NonDeterministicError } [2m[3mtask_queue[0m[2m=[0mcw1_organization_entity_workflows|us-east-2.logixboard.com [3mrun_id[0m[2m=[0m""5c97d62f-71b8-482d-a846-455a496c6e8b"" [3mworkflow_id[0m[2m=[0m""ff8f8f93-05ef-441f-95e4-b2d81954eca3|ORGANIZATION""[0m"
2023-04-06T19:14:19.137Z,"[2m2023-04-06T19:14:18.413676Z[0m [33m WARN[0m [1minstantiate_or_update[0m: [1mtemporal_sdk_core::worker::workflow::managed_run[0m[2m:[0m Error while updating workflow [3merror[0m[2m=[0mNondeterminism(""Search attribute upsert calls must remain deterministic, but SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} } does not match the attributes from history: SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""type\"": [84, 101, 120, 116], \""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} }"") [2m[3mrun_id[0m[2m=[0mef3a2bee-0f36-49e4-a479-816d703c1906 [3mworkflow_id[0m[2m=[0m36a1f9f5-b53e-459d-8357-bfb4a2b72b8c|ORGANIZATION[0m"
2023-04-06T19:14:19.137Z,"[2m2023-04-06T19:14:18.398143Z[0m [33m WARN[0m [1minstantiate_or_update[0m: [1mtemporal_sdk_core::worker::workflow::managed_run[0m[2m:[0m Error while updating workflow [3merror[0m[2m=[0mNondeterminism(""Search attribute upsert calls must remain deterministic, but SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} } does not match the attributes from history: SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""type\"": [84, 101, 120, 116], \""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} }"") [2m[3mrun_id[0m[2m=[0m5c97d62f-71b8-482d-a846-455a496c6e8b [3mworkflow_id[0m[2m=[0mff8f8f93-05ef-441f-95e4-b2d81954eca3|ORGANIZATION[0m"
2023-04-06T19:14:19.137Z,"[2m2023-04-06T19:14:18.393380Z[0m [33m WARN[0m [1mnext_workflow_activation[0m: [1mtemporal_sdk_core::worker::workflow[0m[2m:[0m Failing workflow task [3mrun_id[0m[2m=[0m76211661-5bc2-4d35-9fdd-200cc36df75b [3mfailure[0m[2m=[0mFailure { failure: Some(Failure { message: ""Error while processing workflow task"", source: ""Nondeterminism error: Search attribute upsert calls must remain deterministic, but SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} } does not match the attributes from history: SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""type\"": [84, 101, 120, 116], \""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} }"", stack_trace: """", encoded_attributes: None, cause: None, failure_info: None }), force_cause: NonDeterministicError } [2m[3mtask_queue[0m[2m=[0mcw1_organization_entity_workflows|us-east-2.logixboard.com [3mrun_id[0m[2m=[0m""76211661-5bc2-4d35-9fdd-200cc36df75b"" [3mworkflow_id[0m[2m=[0m""8e49923b-fcfc-429b-83a1-d7077d3efd97|ORGANIZATION""[0m"
2023-04-06T19:14:19.137Z,"[2m2023-04-06T19:14:18.393278Z[0m [33m WARN[0m [1minstantiate_or_update[0m: [1mtemporal_sdk_core::worker::workflow::managed_run[0m[2m:[0m Error while updating workflow [3merror[0m[2m=[0mNondeterminism(""Search attribute upsert calls must remain deterministic, but SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} } does not match the attributes from history: SearchAttributes { indexed_fields: {\""workflowTypeText\"": Payload { metadata: {\""type\"": [84, 101, 120, 116], \""encoding\"": [106, 115, 111, 110, 47, 112, 108, 97, 105, 110]}, data: [91, 34, 104, 97, 110, 100, 108, 101, 67, 119, 49, 79, 114, 103, 97, 110, 105, 122, 97, 116, 105, 111, 110, 77, 101, 115, 115, 97, 103, 101, 87, 111, 114, 107, 102, 108, 111, 119, 34, 93] }} }"") [2m[3mrun_id[0m[2m=[0m76211661-5bc2-4d35-9fdd-200cc36df75b [3mworkflow_id[0m[2m=[0m8e49923b-fcfc-429b-83a1-d7077d3efd97|ORGANIZATION[0m"
```

**Comment by Sushisource** [comment]
@jcgsville Thanks!

The time window represented is very small, if this is 10 minutes then everything happened in the last few ms. It also shows the NDE preceding the panic, which says to me you're probably right that the error somehow makes the panic more likely (which makes some mild sense to me, the issue could be somehow we evict the workflow from memory after the error, but then something goes to try to use it still somehow and that fails).

It might be a bit before I can seriously dig into this (out of town this week), but I have prepared a mitigation which will at least avoid a panic, though will still result in a task timeout unfortunately - we can potentially ship that if upgrading doesn't cause any improvement for you.

**Comment by jcgsville** [comment]
Our upgrade to 1.7.0 is rolling out now. I'll let you know if we're still seeing panics after the rollout

It would definitely help us if the worker didn't panic. The crashing worker is making our other investigation very difficult.

Thank you for your help while out-of-town! You and the Temporal team has been incredibly gracious and helpful!

**Comment by mjameswh** [comment]
The issue can be reproduced by running the following TypeScript workflow, then sending a query to the workflow (which will force a replay of the workflow):

```
export async function workflow(): Promise<SearchAttributes> {
  upsertSearchAttributes({
    CustomIntField: [1],
  });
  return workflowInfo().searchAttributes;
}
```

Our investigation demonstrated two distinct (though interrelated) issues at play here:

1. In #495 (which was introduced in TS SDK 1.7.0), the `UpsertSearchAttribute` state machine was modified to validate that the Search Attribute's payload is deterministic. This is required to avoid incoherencies when a workflow inspects its own search attributes (ie. `workflowInfo().searchAttributes` in TS SDK).

    Turns out however that the server is silently altering the payload, adding the `metadata.type` if missing. It is this modified payload that gets written to history, meaning that, on replay, the `UpsertSearchAttribute`'s payload produced by the workflow code (which never contains the `metadata.type` property) is guaranteed to be different from the payload coming from history (which always contains the `metadata.type` property).

    This explains the `Nondeterminism error: Search attribute upsert calls must remain deterministic, but SearchAttributes { ... } does not match the attributes from history: SearchAttributes { ... }` error.

2. When non-deterministic errors happens, Core force cache eviction of that workflow. The eviction process implies sending a special Workflow Activation to Lang, and then Lang sending a Workflow Activation Completed event back to Core.

    Now, for some type of non-deterministic errors, including the one described previously, Core would fail to recognize this Workflow Activation Completed as being related to the workflow eviction, and would instead process it as a regular Activation Completion.

    This causes the `Send half of activation complete response not dropped: RecvError(())` error.

**Comment by mjameswh** [comment]
We will provide a new release fixing this issue as soon as possible. In the mean time, we recommend to either downgrade to TS SDK 1.6.1 _or_ not to use the `upsertSearchAttributes` command.

**Comment by mjameswh** [comment]
Regarding the `Nondeterminism(\"UpsertWorkflowSearchAttributesMachine does not handle HistoryEvent(id: 6, Some(MarkerRecorded))\")` error, this most likely comes from replaying this workflow on an older worker. This would normally have been a non-issue, as the workflow would have been rejected by the older worker, and it would eventually be dispatched to a worker of the correct version.

**Comment by jcgsville** [comment]
Thank you for the details @mjameswh 

We've returned to a healthy state first by omitting the upsertSearchAttributes, then by downgrading to 1.6.0 (note I didn't see 1.6.1 in npm for one of the temporal packages)
